version: "3.8"
services:
  webDolibar:
    container_name: app_dolibar
    restart: always
    depends_on:
      - db
    image: donpandix/php_laravel:7.4
    volumes:
      - ./http_dolibar:/var/www/html
    ports: 
      - "80:80"
      
  webSellpoint:
    container_name: app_sellpoint
    restart: always
    depends_on:
      - db
    image: donpandix/php_laravel:8.1
    volumes:
      - ./http_sellpoint:/var/www/html
    ports: 
      - "81:80"

  webSiiProxy:
    container_name: app_proxy
    restart: always
    depends_on:
      - db
    image: donpandix/php_laravel:8.1
    volumes:
      - ./http_proxy:/var/www/html
    ports: 
      - "82:80"


  db:
    container_name: database
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      
